services:
  ui:
    image: tic-tac-toe-ui
    ports:
      - '5001:8080'
    networks:
      - tictactoe-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: UserInterface/Dockerfile
      
  server:
    image: tic-tac-toe-server
    ports:
      - '5000:8080'
    hostname: server
    networks:
      - tictactoe-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: Server/Dockerfile

  db:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - tictactoe-network
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      
  message-queue:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - tictactoe-network
    volumes:
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-log:/var/log/rabbitmq/

volumes:
  db:
  rabbit-data:
  rabbit-log:
    
networks:
  tictactoe-network:
