//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Game.GameMessages", typeof(GameMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось начать игру, попробуйте позже.
        /// </summary>
        public static string GameCreateFailed {
            get {
                return ResourceManager.GetString("GameCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат матча - победил бот.
        /// </summary>
        public static string GameFinished_BotWin {
            get {
                return ResourceManager.GetString("GameFinished.BotWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат матча - ничья.
        /// </summary>
        public static string GameFinished_ItsATie {
            get {
                return ResourceManager.GetString("GameFinished.ItsATie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат матча - победил игрок.
        /// </summary>
        public static string GameFinished_PlayerWin {
            get {
                return ResourceManager.GetString("GameFinished.PlayerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти игру, попробуйте позже или создайте новую.
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор в этом поле уже сделан.
        /// </summary>
        public static string UnableToSetCell_AlreadySet {
            get {
                return ResourceManager.GetString("UnableToSetCell.AlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле отсутствует на этой карте.
        /// </summary>
        public static string UnableToSetCell_UnknownCell {
            get {
                return ResourceManager.GetString("UnableToSetCell.UnknownCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш ход.
        /// </summary>
        public static string YourTurn {
            get {
                return ResourceManager.GetString("YourTurn", resourceCulture);
            }
        }
    }
}
