# This is a generated file. Not intended for manual editing.
services:
  server:
    build:
      context: "C:\\0Repository\\TicTacToe"
      dockerfile: "Server/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Server.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "tic-tac-toe-server:dev"
    ports: []
    volumes:
    - "C:\\Users\\IFalko\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\0Repository\\TicTacToe\\Server:/app:rw"
    - "C:\\0Repository\\TicTacToe:/src:rw"
    working_dir: "/app"
