# This is a generated file. Not intended for manual editing.
services:
  server:
    build:
      context: "C:\\0Repository\\TicTacToe"
      dockerfile: "Server/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "tic-tac-toe-server:dev"
    ports:
    - "127.0.0.1:57085:57100"
    - "127.0.0.1:57285:57300"
    volumes:
    - "C:\\Users\\IFalko\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\0Repository\\TicTacToe\\Server:/app:rw"
    - "C:\\0Repository\\TicTacToe:/src:rw"
    - "C:\\Users\\IFalko\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\IFalko\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_24_01_21_03:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  ui:
    build:
      context: "C:\\0Repository\\TicTacToe"
      dockerfile: "UserInterface/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/UserInterface.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "tic-tac-toe-ui:dev"
    ports:
    - "127.0.0.1:57086:57100"
    - "127.0.0.1:57286:57300"
    volumes:
    - "C:\\Users\\IFalko\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\0Repository\\TicTacToe\\UserInterface:/app:rw"
    - "C:\\0Repository\\TicTacToe:/src:rw"
    - "C:\\Users\\IFalko\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\IFalko\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_24_01_21_03:/var/opt/rider-debugger:rw"
    working_dir: "/app"
